export { LOGIN_REQUEST } from "./auth";
export {
  CREATE_AUTHOR,
  GET_AUTHORS,
  GET_AUTHOR_BY_ID,
  UPDATE_AUTHOR,
  DELETE_AUTHOR,
  GET_AUTHORS_PAGINATED,
} from "./authors";

export {
  CREATE_BOOK,
  DELETE_BOOK,
  GET_BOOK_BY_ID,
  GET_BOOKS,
  UPDATE_BOOK,
  GET_BOOKS_PAGINATED,
  GET_BOOKS_BY_NAME,
} from "./books";

export { GET_CATEGORIES, CREATE_CATEGORY } from "./categories";

export {
  CREATE_FAVORITE,
  GET_FAVORITES,
  REMOVE_FAVORITE,
  GET_FAVORITE,
} from "./favorites";

export {
  CONFIRM_PURCHASE,
  CREATE_CHECKOUT_ORDER,
  DELETE_FROM_CHECKOUT,
  GET_CHECKOUT,
  GET_RENTALS,
  RETURN_BOOK,
  GET_ONE_CHECKOUT_OR_RENTED,
} from "./rents";

export {
  CREATE_REVIEW,
  DELETE_REVIEW,
  GET_USER_REVIEWS,
  UPDATE_REVIEW,
} from "./reviews";

export { CHANGE_IMAGE, CREATE_USER, GET_USER, UPDATE_USER } from "./users";
