version: "3.1"
services:
  react:
    build: .
    container_name: react
    networks:
      - frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - .:/usr/react
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  frontend:
    name: frontend
    external: true
